---
- name: Deploy files to remote servers with conditional backup and confirmation
  hosts: all
  become: true
  vars_files:
    - files_to_transfer.yml

  vars:
    backup_dir: "/PF_NAS/UNYO/transfer_backups"
    new_distribution_items: []
    overwrite_items: []

  tasks:
    - name: Initialize new_distribution_items and overwrite_items
      set_fact:
      delegate_to: localhost
      run_once: true

    - name: Process each file distribution item
      include_tasks: single.yml
      loop: "{{ files_to_transfer }}"
      loop_control:
        loop_var: item


    #############################
    # 新規配布処理
    #############################
    - name: Show new_distribution_items
      debug:
        var: new_distribution_items
      when: new_distribution_items|length > 0

    - name: Confirm new file distribution globally
      pause:
        prompt: "【新規配布】ファイルを配布しますか？(yes/no)"
      register: new_distribution_confirm_result
      delegate_to: localhost
      run_once: true

    - name: Distribute new files after global confirmation
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: "{{ item.owner | default('root') }}"
        group: "{{ item.group | default('root') }}"
        mode: "{{ item.mode }}"
      with_items: "{{ new_distribution_items }}"
      loop_control:
        loop_var: item
      when:
        - new_distribution_items|length > 0
        - new_distribution_confirm_result.user_input == 'yes'


    #############################
    # 上書き処理
    #############################
    - name: Show overwrite_items
      debug:
        var: overwrite_items
      delegate_to: localhost
      when: overwrite_items|length > 0

    - name: Confirm overwriting files globally
      pause:
        prompt: "【上書き配布】ファイルを上書きしますか？(yes/no)"
      register: overwrite_confirm_result
      delegate_to: localhost
      run_once: true


    - name: Overwrite files after global confirmation
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: "{{ item.owner | default('root') }}"
        group: "{{ item.group | default('root') }}"
        mode: "{{ item.mode }}"
      with_items: "{{ overwrite_items }}"
      loop_control:
        loop_var: item
      when:
        - overwrite_items|length > 0
        - overwrite_confirm_result.user_input == 'yes'
