---
- name: Deploy files to remote servers with conditional backup and confirmation
  hosts: all
  become: true
  vars_files:
    - files_to_transfer.yml

  vars:
    backup_dir: "/PF_NAS/UNYO/transfer_backups"

  tasks:
    - name: Process each file distribution item
      include_tasks: single.yml
      loop: "{{ files_to_transfer }}"
      loop_control:
        loop_var: item
